### ISSUE TITLE
[依頼]ChatSpace挙動確認

### ISSUE THREAD

**Issue by MugiOka** [MugiOka/chat-space#8]
# IPアドレス
18.177.210.0

**Comment by miyu-yamamoto** [comment]
岡さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ 見本とカラーが異なる部分があるので修正してください**
<img width="1252" alt="スクリーンショット 2020-03-27 14 24 44" src="https://user-images.githubusercontent.com/59544869/77724861-559baf80-7037-11ea-89f4-e10cc62a73ec.png">

`↓こちらが見本です`
<img width="1134" alt="スクリーンショット 2020-03-27 14 29 55" src="https://user-images.githubusercontent.com/59544869/77724939-81b73080-7037-11ea-8034-12aa4e19b01d.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
